- page.py
- pages/base.py
- pages/resultset.py
- requirements.txt
- tests/test_unclassified_job.py
> Created requirements file and initial tests to find job failure and open the log

- pages/resultset.py
> Updated locators for issue #10

- pages/resultset.py
- tests/test_unclassified_job.py
> Added unclassified failure verification addresses Issue #14

- tests/test_unclassified_job.py
Addresses comment from pull #17, https://github.com/mozilla/treeherder-tests/pull/17/files#r43913236
> updated unclassified count assert

- .travis.yml
- pages/base.py
- pages/resultset.py
- setup.cfg
- tests/test_unclassified_job.py
This will likely need rebasing after other pulls land, and I there's likely to be a failure here that I will address in an upcoming patch.
Pinging @tojonmz and @rbillings for review.
> Set up flake8 checking with Travis-CI and resolve warnings

- pages/treeherder.py
- requirements.txt
- tests/conftest.py
- tests/test_login.py
> Created login test

- pages/base.py
- tests/test_login.py
I'm not sure why I merged the original login commit as half of it was missing. This fixes it so the test passes.
> Updated login test

- pages/treeherder.py
- tests/test_pin_job.py
- tests/test_view_single_result.py
Introduces ResultSet and Job page regions. Compares job symbols when pinning them.
@rbillings r?
> Improve stability of tests

- pages/treeherder.py
This should solve an intermittent failure when switching repository.
@rbillings r?
> Wait for page to load after switching repository

- pages/treeherder.py
- tests/test_pin_job.py
- tests/test_switch_repo.py
- tests/test_treeherder_menu.py
- tests/test_unclassified_job.py
Create a test to pin all jobs in a test result, addresses issue #6
> Pin all jobs

- tests/test_login.py
- tests/test_pin_job.py
- tests/test_unclassified_job.py
- tests/test_view_single_result.py
> Removed test classes

- pages/treeherder.py
Updated test locators for pin all jobs in a resultset, and pinning a job from job details. Changes were made in https://github.com/mozilla/treeherder/pull/1484.
> Updated pin job locators

- pages/treeherder.py
- tests/test_add_new_jobs.py
Addresses issue #67 , test for adding new jobs.
> Add new jobs

- requirements.txt
> Update pytest-xdist to 1.15.0

- pages/treeherder.py
- tests/test_range.py
> Test for moving jobs to top or bottom of range

- pages/treeherder.py
- tests/test_expanding_group_count.py
- tests/test_job_counts.py
> New test verifies expanding a group of jobs

- pages/treeherder.py
- tests/test_get_next_results.py
> Test page loads next results

- requirements.txt
@rbillings r?  this allows us to pick up point-release updates to pytest, without having to go through pull requests :-)
> Version pytest to pick-up point-release compatible versions

- pages/treeherder.py
- tests/test_filter_jobs.py
> Test to filter platform

- pages/treeherder.py
- tests/test_pin_job.py
Fixes issue #47 
*Note: two save methods were used as the primary save button was not entering bug data into the job details panel.
> New test adding a bug to the pinboard

- pages/treeherder.py
- tests/test_filter_panel.py
All test have passed. 
IMO code is unoptimized. All feedback appreciated :)
> Test the Filter Panel

- pages/treeherder.py
- tests/test_filter_job_by_keywords.py
Test for Issue #52.
Waiting for the feedback and review :)
> Test: Filter by job keywords

- tox.ini
@rbillings @davehunt r?
Ad-hoc job here: http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/treeherder.adhoc/21/console
> Update PyPOM to 1.1.1

- Jenkinsfile
- tox.ini
@m8ttyB r?
http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/treeherder.adhoc/17/
> Pass PYTEST_BASE_URL through to pytest

- README.md
Removed requires and added badge links, for issue #101
> Updated pyup.io badge links

- README.md
@rbillings r?  preview here: https://github.com/stephendonner/treeherder-tests/tree/readme-link-fixes
> Readme link fixes

- pages/treeherder.py
- tests/test_filter_jobs.py
- tests/test_keyboard_shortcuts.py
Keyboard shortcuts for issue #57 , beginning with selections for next and previous job.
> Keyboard shortcuts for next and previous job

- pages/treeherder.py
- tests/test_keyboard_shortcuts.py
> Added shorcut tests for panels and quick filter

- pages/treeherder.py
- tests/test_keyboard_shortcuts.py
Depends on #120 , but this should fix the current Jenkins errors on test_view_single_result.py.
> View single result test fix

- pages/treeherder.py
- tests/test_keyboard_shortcuts.py
Depends on #120, hopefully adds some stability to test_range.py
> Attempt to fix flaky test_range test
